# Generated by Django 5.2.7 on 2025-11-27 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('folio', models.CharField(max_length=20)),
                ('subtotalc', models.IntegerField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_producto', models.CharField(max_length=60)),
                ('desc_producto', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.IntegerField()),
                ('aro', models.IntegerField()),
                ('apernadura', models.CharField(max_length=7)),
                ('ancho', models.CharField(max_length=5)),
                ('offset', models.IntegerField()),
                ('centro_llanta', models.CharField(max_length=5)),
                ('sprite_360', models.ImageField(blank=True, null=True, upload_to='sprites/')),
                ('sprite_cols', models.IntegerField(default=6)),
                ('sprite_rows', models.IntegerField(default=6)),
                ('sprite_total', models.IntegerField(default=36)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Porsche', 'Porsche'), ('Volkswagen', 'Volkswagen')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('cilindrada', models.DecimalField(decimal_places=1, help_text='Ejemplo: 2.0', max_digits=4)),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_compra', models.IntegerField()),
                ('precio_und', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal_prod', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_compra', to='krd_app.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krd_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='prodimagen')),
                ('es_principal', models.BooleanField(default=False)),
                ('es_360', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='krd_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krd_app.producto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krd_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krd_app.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='krd_app.venta')),
            ],
        ),
    ]
