# Generated by Django 5.1.3 on 2025-09-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='aro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='offset',
            field=models.IntegerField(),
        ),
    ]
