# Generated by Django 5.1.3 on 2025-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd_app', '0004_compra_productocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Porsche', 'Porsche'), ('Volkswagen', 'Volkswagen')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('cilindrada', models.DecimalField(decimal_places=1, help_text='Ejemplo: 2.0', max_digits=4)),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='productocompra',
            name='precio_und',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productocompra',
            name='subtotal_prod',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
